# src/main/resources/META-INF/mods.toml
modLoader="javafml"
loaderVersion="[4.0.31,)"
license="MIT"

# Optional but nice to have:
displayURL="https://github.com/zerogee00/backpack-mod"
issueTrackerURL="https://github.com/zerogee00/backpack-mod/issues"

[[mods]]
modId="backpack"
# if you use Gradle to expand the jar version, keep this so it stays in sync
version="${file.jarVersion}"
displayName="Backpack"
authors="DoktorOdd"
# Optional: provide a 256x256-ish PNG if you want a logo on the Mods screen
# logoFile="assets/backpack/textures/gui/logo.png"

# Keep this short; the launcher shows it in a small panel.
description='''
Lightweight backpack with integrated 3×3 crafting grid, recipe book access,
and 27-slot internal storage. Supports player inventory + hotbar layout.

New: Backpack can be dyed in-world. Sneak + Use while holding any vanilla dye
to recolor. Uses a dyeable overlay texture for tinting while preserving metal
buckles.
'''

# Hard deps
[[dependencies.backpack]]
modId="neoforge"
mandatory=true
versionRange="[21.1.77,22)"
ordering="NONE"
side="BOTH"

[[dependencies.backpack]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

# If you integrate with Curios later, you can add it as a soft/optional dep:
# [[dependencies.backpack]]
# modId="curios"
# mandatory=false
# versionRange="[9.5.0,)"
# ordering="NONE"
# side="BOTH"
